name: Run Python Script

on:
  workflow_dispatch:

env:
  token_secret: ${{secrets.TOKEN_SECRET}}
  
jobs:
  run-python:
    runs-on: ubunto-lastest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Run Python Script
        run: |
          pip install requests
          python Home.py
